### ISSUE TITLE
Background music not playing automatically on page reload

### ISSUE THREAD

**Issue by g-ravity** [g-ravity/amazeing#1]
**Type of Issue**: Bug

**Steps to Reproduce**:
1. Open the project URL in Chrome ( bug not checked in other browsers )
2. The background music starts when the page is finished loading
3. Reload the page
4. Now the background music doesn't start automatically. It starts after the audio button is clicked twice

Most probably the bug is occurring because Chrome restricts playing any kind of media in a website before some user interaction

**Comment by Sean-HL-Lin** [comment]
I'm working on it

**Comment by g-ravity** [comment]
Go ahead!

**Comment by mvarendorff** [comment]
Note for firefox: Music doesn't start on first page load nor reload and only works after clicking the audio button.

If that helps any, this is an article explaining the source of the issue: https://hacks.mozilla.org/2019/02/firefox-66-to-block-automatically-playing-audible-video-and-audio/

**Comment by g-ravity** [comment]
As I understand, both Chrome and Firefox block media autoplay without any user interaction first. I had digged around this issue for a while, but couldn't find a viable solution

**Comment by Sean-HL-Lin** [comment]
didn't figure out... anybody wanna try, go ahead

**Comment by g-ravity** [comment]
@Sean-HL-Lin I'm unassigning you from the issue then

**Comment by iamanishagarwal** [comment]
I would like to work on this issue

**Comment by g-ravity** [comment]
Okay, I'm assigning this to you
