### ISSUE TITLE
Update the Avatar cards

### ISSUE THREAD

**Issue by g-ravity** [g-ravity/amazeing#2]
**Type of Issue**: Enhancement

**Feature List:**
- [x] Design a proper modal for the case where someone presses **'Continue'** button without selecting an Avatar
- [x] Clicking on a selected avatar again should deselect it
- [x] When an avatar is selected, hovering over it should not bring up the description
- [x] Update the hover animation on avatar cards, first the image should fade out, and after some delay the description should fade in and slide up

**Comment by jasbindar-singh** [comment]
I am working on it

**Comment by g-ravity** [comment]
Thanks a lot, go ahead!

**Comment by jasbindar-singh** [comment]
All the features are added.

**Comment by g-ravity** [comment]
Thanks for the contributions. I'll merge the PR soon
